# Generated by Django 4.1.6 on 2023-02-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='student.student'),
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
    ]
