# Generated by Django 4.1.6 on 2023-02-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_skills_student_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='student',
            new_name='stud',
        ),
    ]
