# Generated by Django 4.1.6 on 2023-02-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Enterprenuer', 'Enterprenuer'), ('Higher Studies', 'Higher Studies'), ('Job', 'Job'), ('Others', 'Others')], default='Job', max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('alumnus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10, null=True)),
                ('salary', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(max_length=20)),
                ('alumnus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.RemoveField(
            model_name='placements',
            name='alumnus',
        ),
        migrations.RemoveField(
            model_name='higherstudies',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='higherstudies',
            name='start_year',
        ),
        migrations.AddField(
            model_name='higherstudies',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='higherstudies',
            name='yearofgrad',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='higherstudies',
            name='alumnus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni'),
        ),
        migrations.AlterField(
            model_name='higherstudies',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='higherstudies',
            name='degree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='higherstudies',
            table='higherstudies',
        ),
        migrations.DeleteModel(
            name='Internships',
        ),
        migrations.DeleteModel(
            name='Placements',
        ),
    ]
