# Generated by Django 4.1.6 on 2023-02-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_category_job_remove_placements_alumnus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
