# Generated by Django 4.1.6 on 2023-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
