# Generated by Django 4.1.6 on 2023-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_job_role_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='higherstudies',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
