# Generated by Django 4.1.6 on 2023-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_higherstudies_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higherstudies',
            name='specialization',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('Data Science', 'Data Science'), ('Computer Vision', 'Computer Vision'), ('Natural Language processing', 'Natural Language processing'), ('Marketing', 'Marketing'), ('Finance Systems', 'Finanace Systems'), ('IOT', 'IOT'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('Consultancy', 'Consultancy'), ('Finanace', 'Finanace'), ('Software Developer', 'Software Developer'), ('Data Analyst', 'Data Analyst'), ('Network Security', 'Network Security'), ('Cloud Computing ', 'Cloud Computing'), ('IT project management', 'IT project management'), ('AI and ML', 'AI and ML'), ('others', 'others')], max_length=50, null=True),
        ),
    ]
