# Generated by Django 4.1.6 on 2023-02-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_higherstudies_specialization_alter_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='higherstudies',
            name='degree',
            field=models.CharField(choices=[('M Tech', 'M Tech'), ('MSc', 'MSc'), ('MBA', 'MBA'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('Consultancy', 'Consultancy'), ('Finance', 'Finance'), ('Software Developer', 'Software Developer'), ('Data Analyst', 'Data Analyst'), ('Network Security', 'Network Security'), ('Cloud Computing', 'Cloud Computing'), ('IT project management', 'IT project management'), ('AI and ML', 'AI and ML'), ('others', 'others')], max_length=50, null=True),
        ),
    ]
