# Generated by Django 4.1.4 on 2023-02-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
